# Generated by Django 2.1 on 2018-08-17 09:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_buffer_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={0: 0}),
        ),
    ]
